# Generated by Django 3.1.4 on 2021-01-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
